### ISSUE TITLE
Failed to find chromium executable

### ISSUE THREAD

**Issue by FraH90** [kylon/Sharedown#63]
On the latest version, 5.2.2, it doesn't even open the browser on windows, it says "failed to find chromium executable"
I'm using the installer version.

**Comment by kylon** [comment]
can't reproduce

windows 10, sharedown setup, working as expected once installed

try to uninstall it and delete its data folder (C:\Users\\`yourUserName`\AppData\Roaming\sharedown)

**Comment by FraH90** [comment]
Ok, seems this happens when you install sharedown as system wide installation (i.e. on program files directory).
Maybe it's something due to permission stuff, you don't have admin permission in those folders.

**Comment by kylon** [comment]
i just install with default setup options, actually dont remember if there are options in windows installer, i ll check

**Comment by beefstew** [comment]
I just downloaded and built a copy of Sharedown but receive an error message while trying to download a SharePoint link:
"failed to find chromium executable"

Sample URL:
https://censored.sharepoint.com/:v:/r/personal/censored_com/Documents/Recordings/filename_Meeting%20Recording.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=d56sZC

I think the issue is due to my lack of a code signing certificate and macOS is blocking access to the chromium executable. I had a similar issue with the manually-installed `yt-dlp` (file present in `PATH`, but error message stating it wasn't; had to allowlist the file via macOS System Settings).

From build logs, I can see:
```
yarn run v1.22.22
$ electron-builder
  • electron-builder  version=26.0.6 os=24.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
Downloading chrome 131.0.6778.108 - 153.9 MB [====================] 100% 0.0s 
chrome (131.0.6778.108) downloaded to /Users/chorn/Documents/src/Sharedown/node_modules/puppeteer/chrome/mac_arm-131.0.6778.108
Downloading chrome-headless-shell 131.0.6778.108 - 88.1 MB [====================] 100% 0.0s 
chrome-headless-shell (131.0.6778.108) downloaded to /Users/chorn/Documents/src/Sharedown/node_modules/puppeteer/chrome-headless-shell/mac_arm-131.0.6778.108
  • executing @electron/rebuild  electronVersion=33.4.0 arch=arm64 buildFromSource=false appDir=./
  • installing native dependencies  arch=arm64
  • preparing       moduleName=keytar arch=arm64
  • finished        moduleName=keytar arch=arm64
  • completed installing native dependencies
  • packaging       platform=darwin arch=arm64 electron=33.4.0 appOutDir=dist/mac-arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v33.4.0/electron-v33.4.0-darwin-arm64.zip size=100 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v33.4.0/electron-v33.4.0-darwin-arm64.zip duration=3.532s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate
```
